### ISSUE TITLE
Caracas se pasa como nombre de variable y no como string.

### ISSUE THREAD

**Issue by pedrouzcategui** [Johanjjbr/30-Proyects-JS#1]
Tienes que pasarlo con "", no como nombre de variable

**Comment by Johanjjbr** [comment]
Gracias, ya corregi el error, el checkWeather("caracas"); estaba escrito como variable y no como cadena, aun asi me di cuenta que esa linea no debe estar en el codigo, el primer valor debe ser escrito por la persona
